// 2026-05-22 Phase 1 team-distribution-roadmap:barrel auto-generated by scripts/gen-design-system-barrel.mjs
// Re-export 主元件 / patterns / hooks / lib(consumers can also use subpath imports per package.json exports map)
// 2026-07-14 API 策展(user 拍板「全部收窄」):components/patterns 改 named re-exports,
//   全部 `<camel>Meta`(componentMeta 建置/稽核 metadata,非 consumer API)收窄出 front-door。
//   *Meta / internal 仍可經 per-component subpath(components/<Dir> 的 index.ts export *)消費。

// ─── Components(named re-exports;/Meta$/ 收窄出 front-door)──────────────
export {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from './components/Accordion/index'
export {
  Alert,
  alertVariants,
} from './components/Alert/index'
export type {
  AlertProps,
} from './components/Alert/index'
export {
  AppShell,
  AppShellAside,
  useAppShell,
} from './components/AppShell/index'
export type {
  AppShellAsideProps,
  AppShellProps,
} from './components/AppShell/index'
export {
  AspectRatio,
} from './components/AspectRatio/index'
export type {
  AspectRatioProps,
} from './components/AspectRatio/index'
export {
  Avatar,
} from './components/Avatar/index'
export type {
  AvatarData,
  AvatarProps,
} from './components/Avatar/index'
export {
  Badge,
  badgeVariants,
} from './components/Badge/index'
export type {
  BadgeCountProps,
  BadgeDotProps,
  BadgeProps,
} from './components/Badge/index'
export {
  Breadcrumb,
  BreadcrumbEllipsis,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from './components/Breadcrumb/index'
export type {
  BreadcrumbEllipsisProps,
  BreadcrumbItemSpec,
  BreadcrumbListProps,
  BreadcrumbSize,
} from './components/Breadcrumb/index'
export {
  BULK_ACTION_BAR_DEFAULT_LABELS,
  BulkActionBar,
} from './components/BulkActionBar/index'
export type {
  BulkActionBarLabels,
  BulkActionBarProps,
} from './components/BulkActionBar/index'
export {
  Button,
  ButtonDivider,
  ButtonGroup,
  ButtonGroupContext,
  buttonVariants,
} from './components/Button/index'
export type {
  ButtonProps,
} from './components/Button/index'
export {
  Calendar,
} from './components/Calendar/index'
export type {
  CalendarEvent,
  CalendarProps,
  CalendarView,
} from './components/Calendar/index'
export {
  Carousel,
  CarouselContent,
  CarouselDots,
  CarouselItem,
  CarouselNext,
  CarouselPrevious,
} from './components/Carousel/index'
export type {
  CarouselApi,
} from './components/Carousel/index'
export {
  ChartContainer,
  ChartLegend,
  ChartLegendContent,
  ChartStyle,
  ChartTooltip,
  ChartTooltipContent,
} from './components/Chart/index'
export type {
  ChartConfig,
} from './components/Chart/index'
export {
  Checkbox,
  CheckboxGroup,
  CheckboxGroupContext,
  checkboxVariants,
} from './components/Checkbox/index'
export type {
  CheckboxGroupProps,
  CheckboxProps,
} from './components/Checkbox/index'
export {
  Chip,
  ChipGroup,
  chipVariants,
} from './components/Chip/index'
export type {
  ChipGroupLayout,
  ChipGroupProps,
  ChipProps,
} from './components/Chip/index'
export {
  CircularProgress,
} from './components/CircularProgress/index'
export type {
  CircularProgressProps,
} from './components/CircularProgress/index'
export {
  Coachmark,
} from './components/Coachmark/index'
export type {
  CoachmarkProps,
} from './components/Coachmark/index'
export {
  Combobox,
} from './components/Combobox/index'
export type {
  ComboboxOption,
  ComboboxProps,
} from './components/Combobox/index'
export {
  DataTable,
  DataTableColumnVisibilityPanel,
  DataTableFilterPanel,
  DataTableSortManager,
  MIN_COLUMN_WIDTH,
  createEmptyFilterTree,
  dataTableFilterMatch,
  dataTableVariants,
  evaluateTree,
  isFilterTreeActive,
} from './components/DataTable/index'
export type {
  Conjunction,
  DataTableColumnVisibilityPanelProps,
  DataTableFilterPanelProps,
  DataTablePaginationOptions,
  DataTableProps,
  DataTableSelection,
  DataTableSortManagerProps,
  FilterCondition,
  FilterGroup,
  FilterTree,
  FilterTreeFlat,
  FilterTreeNested,
} from './components/DataTable/index'
export {
  DatePicker,
  DatePickerRange,
  formatDate,
} from './components/DatePicker/index'
export type {
  DateFormatOptions,
  DatePickerProps,
  DatePickerRangeProps,
} from './components/DatePicker/index'
export {
  DescriptionItem,
  DescriptionList,
} from './components/DescriptionList/index'
export type {
  DescriptionDirection,
  DescriptionItemProps,
  DescriptionListProps,
} from './components/DescriptionList/index'
export {
  Dialog,
  DialogBody,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogOverlay,
  DialogPortal,
  DialogTitle,
  DialogTrigger,
} from './components/Dialog/index'
export type {
  DialogHeaderProps,
} from './components/Dialog/index'
export {
  DropdownMenu,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuPortal,
  DropdownMenuRadioGroup,
  DropdownMenuRadioItem,
  DropdownMenuSeparator,
  DropdownMenuShortcut,
  DropdownMenuSub,
  DropdownMenuSubContent,
  DropdownMenuSubTrigger,
  DropdownMenuTrigger,
  floatingLayerClass,
} from './components/DropdownMenu/index'
export type {
  DropdownMenuItemProps,
  SizeKey,
} from './components/DropdownMenu/index'
export {
  Empty,
} from './components/Empty/index'
export type {
  EmptyProps,
} from './components/Empty/index'
export {
  Field,
  FieldDescription,
  FieldError,
  FieldGroup,
  FieldLabel,
  useFormValidation,
} from './components/Field/index'
export type {
  FieldGroupProps,
  FieldLabelProps,
  FieldProps,
  FormFieldInputProps,
  UseFormValidationOptions,
  UseFormValidationReturn,
} from './components/Field/index'
export {
  FieldControlGroup,
} from './components/FieldControlGroup/index'
export type {
  FieldControlGroupProps,
} from './components/FieldControlGroup/index'
export {
  FileItem,
} from './components/FileItem/index'
export type {
  FileItemProps,
} from './components/FileItem/index'
export {
  FileUpload,
} from './components/FileUpload/index'
export type {
  FileUploadProps,
  FileUploadStatus,
} from './components/FileUpload/index'
export {
  FileViewer,
  registerFileRenderer,
} from './components/FileViewer/index'
export type {
  FileInfo,
  FileRenderer,
  FileRendererCapabilities,
  FileRendererProps,
  FileViewerLabels,
  FileViewerProps,
} from './components/FileViewer/index'
export {
  InlineEdit,
} from './components/InlineEdit/index'
export type {
  InlineEditProps,
  InlineEditRenderProps,
} from './components/InlineEdit/index'
export {
  Input,
} from './components/Input/index'
export type {
  InputProps,
} from './components/Input/index'
export {
  LinkInput,
} from './components/LinkInput/index'
export type {
  LinkInputProps,
} from './components/LinkInput/index'
export {
  NumberInput,
  formatNumber,
} from './components/NumberInput/index'
export type {
  NumberFormatOptions,
  NumberInputProps,
} from './components/NumberInput/index'
export {
  Pagination,
} from './components/Pagination/index'
export type {
  PaginationProps,
} from './components/Pagination/index'
export {
  MultiPersonDisplay,
  PEOPLE_PICKER_LENGTH1_WRAPPER_CLASS,
  PeoplePicker,
  PersonAvatarTag,
  PersonDisplay,
  buildPersonProfileCard,
  getPeoplePickerTagWrapperClass,
  resolvePerson,
} from './components/PeoplePicker/index'
export type {
  PeoplePickerProps,
  PersonData,
  PersonValue,
} from './components/PeoplePicker/index'
export {
  Popover,
  PopoverAnchor,
  PopoverBody,
  PopoverClose,
  PopoverContent,
  PopoverFooter,
  PopoverHeader,
  PopoverTitle,
  PopoverTrigger,
} from './components/Popover/index'
export {
  NAMECARD_DEFAULT_FIELD_KEYS,
  ProfileCard,
  ProfileCardDefaultActions,
} from './components/ProfileCard/index'
export type {
  ProfileCardProps,
} from './components/ProfileCard/index'
export {
  ProgressBar,
} from './components/ProgressBar/index'
export type {
  ProgressBarProps,
} from './components/ProgressBar/index'
export {
  RadioGroup,
  RadioGroupItem,
  radioItemVariants,
} from './components/RadioGroup/index'
export type {
  RadioGroupItemProps,
  RadioGroupProps,
} from './components/RadioGroup/index'
export {
  Rating,
} from './components/Rating/index'
export type {
  RatingProps,
} from './components/Rating/index'
export {
  ScrollArea,
  ScrollBar,
} from './components/ScrollArea/index'
export {
  SegmentedControl,
  SegmentedControlItem,
  segmentedControlItemVariants,
  segmentedControlVariants,
} from './components/SegmentedControl/index'
export type {
  SegmentedControlItemProps,
  SegmentedControlProps,
  SegmentedControlSize,
} from './components/SegmentedControl/index'
export {
  Select,
} from './components/Select/index'
export type {
  SelectGroupConfig,
  SelectOption,
  SelectProps,
} from './components/Select/index'
export {
  Separator,
} from './components/Separator/index'
export {
  Sheet,
  SheetBody,
  SheetClose,
  SheetContent,
  SheetDescription,
  SheetFooter,
  SheetHeader,
  SheetOverlay,
  SheetPortal,
  SheetTitle,
  SheetTrigger,
  handleSheetOpenAutoFocus,
  sheetVariants,
} from './components/Sheet/index'
export {
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarGroup,
  SidebarGroupAction,
  SidebarGroupContent,
  SidebarGroupLabel,
  SidebarHeader,
  SidebarInput,
  SidebarMenu,
  SidebarMenuAction,
  SidebarMenuBadge,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarMenuSkeleton,
  SidebarProvider,
  SidebarSeparator,
  SidebarTrigger,
  useSidebar,
} from './components/Sidebar/index'
export {
  Skeleton,
} from './components/Skeleton/index'
export {
  Slider,
  sliderRootVariants,
} from './components/Slider/index'
export type {
  SliderProps,
} from './components/Slider/index'
export {
  StepContent,
  StepDescription,
  StepItem,
  StepLabel,
  Steps,
  stepItemVariants,
  stepsRootVariants,
} from './components/Steps/index'
export type {
  StepContentProps,
  StepContentState,
  StepDescriptionProps,
  StepItemProps,
  StepLabelProps,
  StepsExpansion,
  StepsOrientation,
  StepsProps,
  StepsSize,
} from './components/Steps/index'
export {
  Switch,
  switchVariants,
} from './components/Switch/index'
export type {
  SwitchProps,
} from './components/Switch/index'
export {
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
  tabsTriggerVariants,
} from './components/Tabs/index'
export type {
  TabsListProps,
  TabsSize,
  TabsTriggerProps,
} from './components/Tabs/index'
export {
  Tag,
  tagVariants,
} from './components/Tag/index'
export type {
  TagProps,
} from './components/Tag/index'
export {
  Textarea,
  textareaVariants,
} from './components/Textarea/index'
export type {
  TextareaProps,
} from './components/Textarea/index'
export {
  TimePicker,
} from './components/TimePicker/index'
export type {
  DisabledTimeResult,
  TimeFormatOptions,
  TimePickerProps,
} from './components/TimePicker/index'
export {
  Toaster,
  toast,
} from './components/Toast/index'
export type {
  ToastOptions,
  ToastVariant,
  ToasterProps,
} from './components/Toast/index'
export {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from './components/Tooltip/index'
export {
  TreeItem,
  TreeView,
  treeItemVariants,
} from './components/TreeView/index'
export type {
  TreeDragEndEvent,
  TreeDropPosition,
  TreeItemProps,
  TreeReorderAnnouncements,
  TreeViewProps,
} from './components/TreeView/index'

// ─── Patterns(named re-exports;/Meta$/ 收窄出 front-door)────────────────
export {
  AVATAR_SIZE,
  ICON_SIZE,
  INLINE_ACTION_HOVER_BG_SIZE,
  ItemAvatar,
  ItemContent,
  ItemIcon,
  ItemInlineAction,
  ItemInlineActionButton,
  ItemLabel,
  ItemPrefix,
  ItemSuffix,
  ROW_PADDING_BY_SIZE,
  RowSizeProvider,
  getUniformPrefixSlotStyle,
  itemPrefixAlignVariants,
  useRowSize,
} from './patterns/element-anatomy/index'
export type {
  InlineActionConfig,
  ItemAvatarProps,
  ItemContentProps,
  ItemIconProps,
  ItemInlineActionButtonProps,
  ItemInlineActionProps,
  ItemSuffixHoverGroup,
  ItemSuffixProps,
  RowSize,
} from './patterns/element-anatomy/index'
export {
  ChromeHeader,
  HEADER_TABS_SLOT_WRAPPER_CLASS,
} from './patterns/header-canonical/index'
export type {
  ChromeHeaderProps,
} from './patterns/header-canonical/index'
export {
  ResizeHandle,
} from './patterns/resize-handle/index'
export type {
  ResizeHandleProps,
} from './patterns/resize-handle/index'

// ─── Internal(subpath-only,排除 root front-door per dim-72 SSOT)─────────────
// 下列 internal 元件/pattern 不在 root barrel front-door;只能 subpath import
// (@qijenchen/design-system/{components,patterns}/<Dir>),「包裝後 + 自行確認」才可用。
// SSOT = 各自 spec.md frontmatter isInternal。改公開/內部請改 frontmatter 後重跑本 generator。
//   - components/Command
//   - components/DateGrid
//   - components/HoverCard
//   - components/Menu
//   - components/Notice
//   - components/OverflowIndicator
//   - components/SelectMenu
//   - components/SelectionControl
//   - patterns/horizontal-overflow
//   - patterns/overlay-surface

// ─── Tokens(JS mirrors — token SSOT 程式面)──────────────────────────────
export * from './tokens/categorical-color'
export * from './tokens/elevation/overlay-geometry'
export * from './tokens/motion/motion'
export * from './tokens/motion/overlay-motion'
export * from './tokens/uiSize/icon-size'

// ─── Hooks ────────────────────────────────────────────────────────────────
export * from './hooks/use-controllable'
export * from './hooks/use-is-narrow-viewport'
export * from './hooks/use-is-touch-device'
export * from './hooks/use-overflow-items'

// ─── Lib utilities ────────────────────────────────────────────────────────
export * from './lib/drag-visual'
export * from './lib/multi-select-ordering'
export * from './lib/utils'
